coder:
  persona: |
    You are an expert coder.
  model: flow-openai-gpt-4o
  context:
    mode: compact
    scope: selected
    selection:
      model: flow-gemini-2.0-flash
      step: 10
      limit: 20